### ISSUE TITLE
support for ACL

### ISSUE THREAD

**Issue by drzraf** [danny0838/git-store-meta#1]
ACL are pretty useful on a web-server using Git working-copy to serve applications.
Eg, instead of messing with adm, staff and other groups, `setfacl -m -R u:www-data:rX css/` does the trick.

But ACL are not part of the metadata supported neither by setgitperms.perl nor by git-store-meta.
Is there any plan to implement it?
If not, would you accept a patch for this?
How would you like to define a store format for them? (getfacl and setfacl already provide a store/restore mechanism)

**Comment by danny0838** [comment]
Sorry for missing this topic and delayed reply. Currently there is not a plan for implementing it, but it's free for you to fork or to patch it.

If you are willing to patch it, currently I personally prefer using a field name `facl` with field value format like `u:www-data:rX g:mygroup1:rx` (i.e. space separated values). But I really havn't think much about this, and it's free for you to modify it.

**Comment by danny0838** [comment]
Added this feature in 048c3f0acf8344beba32ce1b22cf961bc8a4df2a.

**Comment by drzraf** [comment]
Great!
I will test that soon.

thank you
