### ISSUE TITLE
Update metadata after git pull or merge

### ISSUE THREAD

**Issue by VadimKulagin** [danny0838/git-store-meta#12]
I noticed that now there is no update of metadata after the execution of `git pull` or` git merge`.
To make the upgrade work after `git pull` or` git merge`, I had to add a new `post-merge` hook:
```bash
#!/usr/bin/env bash
# It runs .git/hooks/git-store-meta.pl --apply -d after `git merge` or `git pull`

if [ -x ".git/hooks/git-store-meta.pl" ]; then
    # apply meta changes of files and directories
    .git/hooks/git-store-meta.pl --apply -d
fi
```

It would be very convenient if such a hook appeared immediately after the installation of git-store-meta.pl --install.
What do you think?

**Comment by danny0838** [comment]
Implemented in 1.2.5.
