### ISSUE TITLE
Update action uses wrong timestamp for parent directory on file deletion

### ISSUE THREAD

**Issue by ha-ju** [danny0838/git-store-meta#19]
I appreciate [git-store-meta](https://github.com/danny0838/git-store-meta) very much: It is compact, efficient, very valuable, and it is all in one file. Great work!

However there is an issue with the the way in which the "update action with directories"

`--update --directory`

of release 1.3.1 handles the modification timestamps of parent directories of deleted files:

Deleting a file changes the parent directory so that the latter's modification timestamp is updated. However, the placeholder scheme in the function `update` in `git-store-meta.pl` reuses the old entry for the directory in the meta-file in this case. As a consequence, after committing the deletion and a later checkout of that commit, the directory timestamp is the old one from prior the deletion instead the one that is generated by the deletion.

This behavior of release 1.3.1 can be reproduced like so:

   * Create a new repository, install [git-store-meta 1.3.1](https://github.com/danny0838/git-store-meta/releases/tag/1.3.1) together with its own hook scripts (`--install`), and equip the `--update` and `--store` commands in the pre-commit hook script with the `--directory` option.

   * Create a directory `dir` in the top directory of the working tree, and therein (in `dir`) two files: `one` and `two`. Stage all, and commit the creation. Let's designate this commit with A.

   * Remember the modification timestamp of `dir` in the working tree at this moment. Let's call it T1.

   * Delete file `dir/two` and stage and commit the deletion. Let this is be commit B.

   * Remember the modification timestamp of `dir` in the working tree at this moment: Let's call it T2.

   * Checkout commit A and after that commit B.

   * Note that the modification timestamp of `dir` in the working tree is now T1 while it should be T2.

As a workaround for users that suffer from this, one can use the `--store` action instead of `--update`.

Once again: Thank you for this great piece of software!

**Comment by danny0838** [comment]
Fixed. Thank you for reporting.
