### ISSUE TITLE
sh: getfacl: command not found on OS X

### ISSUE THREAD

**Issue by priyadarshan** [danny0838/git-store-meta#2]
Hello,

Thank you for git-store-meta. This is exactly what I have been looking for.

Testing it on OS X, it throws error, since OS X does not have `getfacl` and `setfacl`
```
sh: getfacl: command not found
```

I suspect the same would happen on *BSD platforms.

Would it be possible to switch off the acl part by default, or at least to provide a switch to disable it, so that ?

Thank you again.

**Comment by danny0838** [comment]
Released 1.2.1, which should have fixed this issue.

**Comment by priyadarshan** [comment]
Thank you so much, it works perfectly now.
