### ISSUE TITLE
Handle --directory analogously to the fields

### ISSUE THREAD

**Issue by ha-ju** [danny0838/git-store-meta#21]
This feature request is strongly related to issue #20 by lozobo:

If I understand correctly, lozobo proposes to determine the fields to be stored at install time. This would be also very useful for the `--directory` option, i.e. the question whether or not meta-data of directories are to be stored.

Right now, the option `--directory` has to be specified on every call to git-store-meta: On `--install`, `--store`, `--update`, and `--apply`. Apart from being kind of inconvenient on manual use, it bears the risk to be forgotten.

In case of an `--update`, a forgotten `--directory` might lead to outdated directory data in the meta-data file, which might nevertheless be applied by the post-checkout and post-merge hooks, where the `--directory` option is hard-wired (if used at all).

This raises a more general question of design: Would it not be a good idea to store the decision whether or not to store directory information (the --directory option), within the meta-data file, quite analogously to the information which meta-data fields are to be stored?

In fact, with respect to the user interface one could combine the `--field` option and the `--directory` option to a new, more general option `--info`, which takes the list of all the information that is to be stored as its argument. Therein, the field keywords as well as the new keyword `directory` would be recognized. So the user would say
```
git-store-meta --store --info mtime,mode,directory
git-store-meta --apply --info mtime,mode,directory
```
instead of
```
git-store-meta --store --field mtime,mode --directory
git-store-meta --apply --field mtime,mode --directory
```

Within the meta-data file, one could encode the inclusion of directory data into the header, for example like so:
```
# generated by	git-store-meta	1.3.2
# Includes directory data.
<file>	<type>	<mtime>
...
```
versus
```
# generated by	git-store-meta	1.3.2
# Disregards directory data.
<file>	<type>	<mtime>
...
```

This would make the option `--directory` obsolete for the `--update` action, as the latter would only rely on the information stored in the meta-data file with respect to the inclusion of directory data, as it does for the fields.

The same applies to the `--apply` action: It would apply what is recorded in the meta-data file, unless an explicit `--info` option specifies what meta-data are to apply instead.

With that, issue #20 could be addressed by making `--info` also available for `--install`: If used in this context, the `--info` option is passed one by one to the `--store` command in the `pre-commit` hook script. That's all.

What do you think?

**Comment by danny0838** [comment]
This is a good idea. However, adding an additional comment line for directory breaks `.git_store_meta` created in previous versions from working, and we need another good design that doesn't break backward compatibility.

An alternative design is to make `directory` a "field", like:

    # generated by	git-store-meta	1.3.2
    <file>	<type>	<mtime>	<directory>
    ...

While the content of `directory` field is empty for all files and directories.

This is more compatible with previous versions, but it's somehow awkward and it takes more bytes (the `<directory>` field and a separator char for every file)...

Anyone has a better idea?

**Comment by ha-ju** [comment]
Maybe one could use the first header line to encode the `directory` "field":
```
# generated by	git-store-meta	1.3.2   respecting dirs
<file>	<type>	<mtime>
...
```
versus
```
# generated by	git-store-meta	1.3.2   skipping dirs
<file>	<type>	<mtime>
...
```
In this way the number of header lines would not change.

I think that there will always be some issues if one tries to handle `directory` exactly as an actual field: It does not really fit in that scheme, because it is a bit of global information rather than something that has to be recorded on a per file basis. However, the approach
```
<file>	<type>	<mtime> <directory>
```
is really tempting...

Another important topic in this context are the constraints that `git-strore-meta.pl` should obey with respect to backward compatibility: Are new versions intended to

* be able to process existing meta-data files,
* be able to be processed by existing hook scripts,
* respect grown user habits with respect to usage (interface, look and feel) (not to be underestimated),
* only imply minor changes in the code (efficiency)?

Of course, this strongly depends on the existing use cases and established workflows, on which I have no idea, and on which of them are intended to be supported. As an example, see the centralized approach that is proposed in issue #17.

**Comment by lozobo** [comment]
From #20:
> If I understand correctly, lozobo proposed to determine the fields to be stored at install time. This is actually a good idea, that should be considered to be extended to the `--directory` option.

In fact, `--directory` it's correctly written in the pre-commit hook.
There is an inconsistency in the post-merge and post-checkout hooks. Here the flag is always written.
From the hook perspective, I think it's the only thing to fix. Than the behaviour will always be consistent.

If you want to store/apply the metadata at every commit/merge, you better use the hooks (which are configured by `--install`).
Otherwise, if it's just a one-time thing, I don't see any good in handling `--directory` as a field.

I'm all-in to save in the metadata-file with what flag it has been created, eg:
`# generated by	git-store-meta	1.3.2   with   --target foo.meta --directory --field user,group
`

I'm surely miss something, but I really don't see the need to change the format and potentially break backward-compatibility.

**Comment by danny0838** [comment]
> From #20:
> 
> In fact, `--directory` it's correctly written in the pre-commit hook.
> There is an inconsistency in the post-merge and post-checkout hooks. Here the flag is always written.
> From the hook perspective, I think it's the only thing to fix. Than the behaviour will always be consistent.

If `--store` has been run without `--directory`, no directory metadata is stored, and `--apply --directory` won't do anything more than applying metadata for files. Therefore, it's always safe to `--apply -d` and there's no need to add a switch for the generated hooks.

> If you want to store/apply the metadata at every commit/merge, you better use the hooks (which are configured by `--install`).
> Otherwise, if it's just a one-time thing, I don't see any good in handling `--directory` as a field.

Unfortunately, there are still cases that hook is not available, such as `git reset --hard`, or a merge with conflict. In such cases an `--apply` with or without `--directory` would need to be run manually, and the issue that "it bears the risk to be forgotten", as @ha-ju mentioned, does exist.

On the other hand, the user may change the fields, or use different fields in different branches in a repo, and having to reinstall the hooks whenever fields are changed would be an issue. As such, I would prefer a solution such that hooks generated by simply `--install` be independent with the .git_store_meta file and works universally.

> I'm all-in to save in the metadata-file with what flag it has been created, eg:
> `# generated by git-store-meta 1.3.2 with --target foo.meta --directory --field user,group `

`--target` is meaningless as git-store-meta can never read the git_store_meta file without knowing the --target in prior, and it's probably the only reasonable one to be added to the `--install`. `--field` is also meaningless as they are already defined in the second line.

    # generated by	git-store-meta	1.4.0	--directory

may be a good idea. But the main issue is to reduce the `--directory` option, and to make a `--field <whatever>,directory` (or `--info` as @ha-ju proposed) be stored in such way is somehow inconsistent and need a special care-taking.

**Comment by ha-ju** [comment]
> On the other hand, the user may change the fields, or use different fields in different branches in a repo, and having to reinstall the hooks whenever fields are changed would be an issue.

Good point from @danny0838, I did not see that. But this also applies to the usage of `--directory` and is an additional motivation to store that option in the mata-data file rather than in the hook scripts.

**Comment by danny0838** [comment]
> Maybe one could use the first header line to encode the `directory` "field":
> 
> ```
> # generated by	git-store-meta	1.3.2   respecting dirs
> <file>	<type>	<mtime>
> ...
> ```
> 
> versus
> 
> ```
> # generated by	git-store-meta	1.3.2   skipping dirs
> <file>	<type>	<mtime>
> ...
> ```
> 
> In this way the number of header lines would not change.

We probably need a more structured representation for the data so that they can be easily interpreted by the script.

> I think that there will always be some issues if one tries to handle `directory` exactly as an actual field: It does not really fit in that scheme, because it is a bit of global information rather than something that has to be recorded on a per file basis. However, the approach
> 
> ```
> <file>	<type>	<mtime> <directory>
> ```
> 
> is really tempting...

On the other hand, it's also inconsistent that entries in the `--info` get stored in either the second line or the first line.

Currently it seems that making everything stored as a "field" is the most generalizable approach and is most consistent and compatible with earlier versions.

Besides, in a broader sense `--fields` can mean "subjects of interests", which doesn't differ much with `--info`. For backward compatibility I'd prefer not changing the name.

> Another important topic in this context are the constraints that `git-strore-meta.pl` should obey with respect to backward compatibility: Are new versions intended to
> 
>     * be able to process existing meta-data files,
> 
>     * be able to be processed by existing hook scripts,
> 
>     * respect grown user habits with respect to usage (interface, look and feel) (not to be underestimated),
> 
>     * only imply minor changes in the code (efficiency)?
> 
This is not an easy question. Our principle is that every version of git-store-meta should be able to process a .git_store_meta file generated by any prior versions. The reason is obvious: .git_store_meta is a data file that may stay forever in the Git repository, and it would be very bad if the user has to install an old git-store-meta version when he checked out an old commit and wants to apply the stored metadata.

Other issue are less significant, we would keep them as compatible as possible but it is possible to break them.

> 
> Of course, this strongly depends on the existing use cases and established workflows, on which I have no idea, and on which of them are intended to be supported. As an example, see the centralized approach that is proposed in issue #17.

**Comment by danny0838** [comment]
[v2.0.0_001](https://github.com/danny0838/git-store-meta/releases/tag/2.0.0_001) is a version dealing with this issue. Feel free to test on it. Note that it is an alpha version, and there's no guarantee that later versions be backward-compatible with it.

**Comment by ha-ju** [comment]
Thank you @danny0838 for the great new release and for thereby resolving this issue.

Seeing it, I also think that encoding the former `--directory` option in the second header line of the meta-data file as
```
<file>	<type>	<mtime> <directory>
```
is the most consistent choice that one could make without complicating things.

It is also a clever move to ensure backward compatibility by using `has_directory_entry` as a criterion for setting the directory field when processing older meta-data files.

Having played around with this new release, I would like to propose some minor changes that are not related to this issue (this one is perfectly resolved, as far as I can see) my means of a pull request (#22), which see.

So far, thank you very much.

**Comment by danny0838** [comment]
Though we already have a nice temporary solution. We are considering changing the `--field directory` to something like `--config|-c directory` and save the directory flag in the first heading line, like:

    # generated by	git-store-meta	2.0.0	directory
    <file>	<type>	<mtime>
    ...

(or maybe `directories` or `<directory>` instead of `directory`) so that we have the advantage of knowing whether handle directories by reading the existing metadata file while not confusing the meaning of fields and writing unnecessary empty field values.

This is also more extensible. For example, we can add a `topdir` option in the future by running `--config|-c directory,topdir`, for example.

**Comment by ha-ju** [comment]
This would be a cleaner approach, since it would separate global parameters from those whose values have to be recorded on a per file basis.

The price for that is additional parsing effort in subroutine `get_cache_header_info`.

To extrapolate that: If future needs force to store more global (config typed) parameters than the first header line of the metadata file can take, one might use a separate config file to maintain them. This would completely separate meta data (payload) from config data, while allowing to stay backward compatible. But this is by no means appropriate for one or two parameters that we discuss now.

So, I like your idea to have two options&mdash;one `--fields` for fields, one `--config` for globals&mdash;and two places to sore them separately within the metadata file.

**Comment by danny0838** [comment]
[2.0.0_004](https://github.com/danny0838/git-store-meta/releases/tag/2.0.0_004) is another implementation. Basically we revert to the legacy usage of `--directory` but store it in the metadata file and load it in the future, and a `--no-directory` is added to revert the behavior.
