### ISSUE TITLE
Processing is slow if there are many files

### ISSUE THREAD

**Issue by dreampet** [danny0838/git-store-meta#23]
My git repo with 16633 files:
root@DESKTOP:~/Share/libs$ git ls-tree -r HEAD | awk '{if($2="blob"){print $0}}' | wc -l
**16633**

Process speed:
![meta_data_slow](https://user-images.githubusercontent.com/12544313/55722465-fcf39100-5a38-11e9-820b-29e97406b092.gif)

**Comment by danny0838** [comment]
I don't get it. What are you trying to process?
