### ISSUE TITLE
Allow to exclude Git submodules

### ISSUE THREAD

**Issue by ha-ju** [danny0838/git-store-meta#24]
This feature is only relevant with the `--directory` option when using **Git submodules:**

It would be nice to have the metadata of submodule top level directories managed from within the submodules instead of by the superproject&mdash;in other words, to have the metadata file of the submodule be in charge for these directories. The benefit would be that the submodule topdir metadata match the commit that is checked out in the submodule rather than the just loosely related commit that happens to be checked out in the superproject.

From the submodule's perspective, this can be easily achieved by using the new `--topdir` option. But this interferes with the `--apply`s that occur in the superproject when commits are checked out there.

To resolve that, it would be useful to have an option `--no-submodules` that can be specified to `git-store-meta` on the superproject level to make it ignore submodule topdirs on `--store`, `--update`, and `--apply`.

What do you think?

**Comment by danny0838** [comment]
I cannot think of any rationale to record top submodule directories in the .git_store_meta of the superproject, and thus we would ignore submodules directly without providing an option, as implemented in [2.0.0_005](https://github.com/danny0838/git-store-meta/releases/tag/2.0.0_005).

BTW, you did a good job finding a use case of `--topdir`. 🙂

**Comment by ha-ju** [comment]
Thank you @danny0838 for implementing this feature, and at that so fast.

> I cannot think of any rationale to record top submodule directories in the .git_store_meta of the superproject, and thus we would ignore submodules directly without providing an option, as implemented in 2.0.0_005.

Right you are!&mdash;Neither do I. This is the right way to go.

> BTW, you did a good job finding a use case of `--topdir`. :slightly_smiling_face:

Well, I kind of like that option... :smirk:
