### ISSUE TITLE
Allow unforced --apply when only submodules are modified

### ISSUE THREAD

**Issue by ha-ju** [danny0838/git-store-meta#25]
This feature is only relevant if **Git submodules** are used:

When a commit of a superproject is checked out and that commit comprises a submodule reference that is different from what was checked out before, Git considers this difference as an unstaged modification to the submodule topdir, so that the superproject working tree is checked out in a dirty state. As a consequence, the unforced `git-store-meta --apply` fails in the `post-checkout` hook.

It would be nice if `--apply` would recognize that such modifications only correspond to mismatching submodule references instead of real changes&mdash;if that is true and nothing else was modified&mdash;and would perform the apply anyway without being forced, i.e. from within the `post-checkout` hook.

**Comment by danny0838** [comment]
Implemented the feature that submodules be ignored for --store, --update, and --apply in 2.0.0_005.

**Comment by ha-ju** [comment]
Thank you @danny0838, again.

I am glad that you have found such an elegant way to implement this kind of submodule support.
