### ISSUE TITLE
Preserve mtime of the metadata file's directory

### ISSUE THREAD

**Issue by ha-ju** [danny0838/git-store-meta#26]
There is an inconvenience when `git-store-meta` records the mtime of the directory that contains the metadata file: These records cause merge conflicts on every non-trivial merge. This is because `--store` and `--update` generate a temporary file within that directory, which bumps the latter's modification timestamp.

The same type of inconvenience would result from recording the mtime of the metadata file itself, which is not done by `git-store-meta` for good reason.

With the development version 2.0.0_005 of `git-store-meta` one encounters this situation when recording mtime (which is the case by default) and combining `--directory` and `--topdir` or combining  `--directory` with a `--target` that lies in a tracked subdirectory that is not a submodule.

As a remedy, I would suggest that `git-store-meta` should preserve the mtime of the directory that contains the metadata file. More precisely: `--store` and `--update` should record that mtime into memory as an early step and restore it when their job is done.

Albeit this would be a cheat in some respect, it would be not different from having the metadata file edited _in place_.

**Comment by danny0838** [comment]
Generate temp file in the .git directory to prevent altering the parent directory of `.git_store_meta`.

**Comment by ha-ju** [comment]
Your idea to use the `.git` directory for the temp file is a much better (cleaner) approach than my proposal. And it woks fine. Thank you @danny0838 for fixing.
