### ISSUE TITLE
pre-commit package integration

### ISSUE THREAD

**Issue by jamesquilty** [danny0838/git-store-meta#27]
I'm starting to use [pre-commit](https://pre-commit.com), a  multi-language package manager for pre-commit hooks, and it seems that there's potential for conflict with git-store-meta's modification of `.git/hooks/pre-commit` and for integration of git-store-meta as a [pre-commit](https://pre-commit.com) plugin. There are several examples of the latter on the pre-commit [Supported hooks](https://pre-commit.com/hooks.html) page.

Would integration with [pre-commit](https://pre-commit.com) provide a way for git-store-meta to avoid conflict with other packages which modify `.git/hooks/pre-commit`?

**Comment by danny0838** [comment]
We are not familiar with `pre-commit`, and it is probably too ad-hoc to handle pre-commit hooks differently to post-checkout and post-merge hooks... So we are unlikely to implement it until someone can provide a good design for this.

**Comment by jamesquilty** [comment]
I've been able to satisfactorily work-around this issue. I don't need integration with pre-commit any more, and it doesn't appear there's been any interest from anyone else, so I'm going to take the liberty of closing this issue.

@danny0838 Thanks for your attention on this, and for sharing git-store-meta in the first place!
