### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by deekej** [danny0838/git-store-meta#31]
Hello there!

I wanted to ask if you would be willing to add any open-source license to this repository? :) I'm really considering using your solution for myself, and I think it will work very nicely. If it does, I would like to package it into Fedora distribution, but I can't do that unless the repository contains a Fedora-compatible open-source license... :)

With kind regards,

Dee'Kej

**Comment by danny0838** [comment]
It's MIT license as written in the [source code](https://github.com/danny0838/git-store-meta/blob/e72f7a053bb6737bb882e002bc4c974ab3af0025/git-store-meta.pl#L51).

We'll consider adding a LICENSE file.

**Comment by deekej** [comment]
> It's MIT license as written in the [source code](https://github.com/danny0838/git-store-meta/blob/e72f7a053bb6737bb882e002bc4c974ab3af0025/git-store-meta.pl#L51).

I see. :) I guess this might got through the approval process, but adding the LICENSE file would certainly make it much easier... ;)

**Comment by danny0838** [comment]
Added.
