### ISSUE TITLE
Apply is slow

### ISSUE THREAD

**Issue by pryvision** [danny0838/git-store-meta#33]
I am using git-store-meta to maintain file ownership and modes. As compared to some other solutions, git-store-meta --store is really fast, taking just 2 seconds on my repository. However, an --apply takes nearly 5 minutes, this is regardless of whether any file ownership actually needs updating. I have considered running --store on the current tree and running a diff of this with the committed metadata to see what actually needs updating. Is there an easier way?

**Comment by danny0838** [comment]
If there's really a difference, it should be better writing the metadata check directly in the code for applying. Here's a [test version](https://github.com/danny0838/git-store-meta/tree/test-lazy-apply) and you can run `--apply --lazy` for lazy applying. However, it doesn't seem to have significant difference by my test. Do you store and apply `facl`?

**Comment by pryvision** [comment]
This works great for me. My metadata is created with:
./git-store-meta.pl --store -f file,type,mtime,mode,uid,gid 

Prior to your patch:
fields: file, type, mtime, mode, uid, gid

real	4m15.141s
user	2m53.906s
sys	1m29.700s

After patch:
fields: file, type, mtime, mode, uid, gid

real	0m3.933s
user	0m2.660s
sys	0m1.272s

Life changing. Thanks a million.

**Comment by danny0838** [comment]
I am wondering why there's such significant performance impact on your device... What is your OS? Is there an antivirus or security software monitoring all attempts to modify file metadata?

I am considering how we should further implement this lazy applying feature. Should it be a `--install --lazy` to install hooks that will apply lazily? Or should it be an option for `--store` to save a `.git_store_meta` with option `--lazy` so the installed hooks will be applied lazily?

A pro for the latter is the ability to set lazy state for individual branch. But I wonder whether lazy applying is preferred is more likely device-specific and thus the former approach matches this better?

Or maybe an option is to not implement the option and just apply lazily anyway. However, this may worsen performance if most files have changed metadata, and we'll need more evaluation.

**Comment by pryvision** [comment]
I am running Debian 11 bullseye on an m.2 NVME drive. There's no antivirus or anything. Maybe the metadata writes have to sync the disk for some reason where as the read can hit the block cache? I am not really sure, but it is indeed way faster with --lazy. 

I have not really explored the hook system for our use case. My gut tells me that people who are using git-store-meta in a docker like scenario, where they always check out clean, are not going to want --lazy, even though i only find it 1% slower than without --lazy on a clean checkout.

 I am almost always doing incremental pulls. So I want to get a single small update from a multigigabyte repository. In this case, --lazy is a life saver.

**Comment by danny0838** [comment]
Implemented in 2.3.1.
