### ISSUE TITLE
Feature request: add time created field

### ISSUE THREAD

**Issue by Taitava** [danny0838/git-store-meta#34]
Hi,

I guess you have already considered this feature, but at least I didn't find anything related to it in the closed issues. I have a repository on Windows and I'd like to store the creation times in addition to modification and access times. I'm not sure if creation times are supported in Linux, for example, or if it's more a Windows specific feature? And I have absolutely no knowledge about the technical implementation, as I'm not familiar with Perl.

Thank you for considering this! :)

**Comment by danny0838** [comment]
ctime is not portable. According to the [perl doc](https://perldoc.perl.org/perlport#Files-and-Filesystems), it's file creation time on Windows, inode change time on Linux, and not supported on Mac OS X.

Additionally, there is no way for Perl to modify the ctime of a file. Even if ctime is stored, it cannot be applied.

**Comment by Taitava** [comment]
Thank you for this information! I understand that implementing this feature would not actually deliver a good quality solution and therefore maybe it's better to leave this out.

As a partial solution to myself, I might consider learning Perl and creating a fork for my own use, where I would implement the Windows file creation time (maybe Linux too). Not being able to modify the ctime of files is something that I would not need in the beginning. Just to be able to have the ctimes stored would be a semi well working solution for me (but maybe not for the general public). If I'll end up creating my own fork, I'll put it to GitHub, but I do not plan to make a pull request because, as mentioned, it would not work in all platforms and it would not have the applying feature.
