### ISSUE TITLE
Trailing white space in .git_store_meta header comment

### ISSUE THREAD

**Issue by jamesquilty** [danny0838/git-store-meta#39]
Commit 92240a5ca17867c0056ae879f7c74eb9bfa1b441 extended `$git_store_meta_header` to append the configuration held in configs`:

https://github.com/danny0838/git-store-meta/blob/f98e886a8316348123452f2bcdd7755e55496e78/git-store-meta.pl#L287-L288

Unfortunately, by default the three components of `$configs` are set to `undef` ([L80-L84](https://github.com/danny0838/git-store-meta/blob/f98e886a8316348123452f2bcdd7755e55496e78/git-store-meta.pl#L80-L84)) and the resulting header then contains the version followed by a trailing tab character. This conflicts with the automatically-enforced [trailing-whitespace](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) pre-commit hook, leading to a deadlock on `git commit`.

Could you please change the `join(...)` in line 288 to avoid appending trailing white space when the `$configs` variable is empty?

**Comment by danny0838** [comment]
Implemented. Thank you for the feedback.
