### ISSUE TITLE
--install should be enough

### ISSUE THREAD

**Issue by weberjn** [danny0838/git-store-meta#40]
Even if one does --install, currently you have to --store or --apply to make git-store-meta.pl create the .git_store_meta
This should be automatically triggered by --install

If there exists already a .git_store_meta (after clone) the options should be taken from the file (e.g. the -d default and fields)

So the workflow would be simply  git init + git-store-meta.pl --install or git clone + git-store-meta.pl  --install

**Comment by danny0838** [comment]
`--install` does not support options while `--store` receives fields and flags. They basically do not do the same thing.

**Comment by weberjn** [comment]
yes, but I meant, install suggests that the script is activated from now on, which -i does not, is it?
so one would need an option like --install-and-activate

**Comment by danny0838** [comment]
No. As the doc says, `--install` means to generate hooks for the REPO to auto store/apply, while `--store` means to generate or regenerate the store file for the COMMIT/BRANCH, with optional fields and flags. They are totally of different scopes and I don't see a good reason to mix them together.

**Comment by weberjn** [comment]
so my workflow is ``git init && git-store-meta.pl --install && git-store-meta.pl --store``

what about ``git-store-meta.pl -i -s`` in one command
or ``git-store-meta.pl --init``  ?

**Comment by johnnyutahh** [comment]
New/ignorant user here with newbie-like question that (I think?) is related to this discussion:

Is `--install` a (per-repo) one-time command and `--store` runs for every `COMMIT/BRANCH`... correct?

> No. As the doc says, `--install` means to generate hooks for the REPO to auto store/apply, while `--store` means to generate or regenerate the store file for the COMMIT/BRANCH, with optional fields and flags. They are totally of different scopes and I don't see a good reason to mix them together.

**Comment by danny0838** [comment]
@johnnyutahh:
> Is `--install` a (per-repo) one-time command and `--store` runs for every `COMMIT/BRANCH`... correct?

Yes. Of course you can selectively store metadata only for the branches you want.

**Comment by danny0838** [comment]
@weberjn As previously mentioned: They are totally of different scopes and I don't see a good reason to mix them together.

**Comment by weberjn** [comment]
OK, technically they are different scopes.
From the user view I want to be bothered as little as possible, set up git-store-meta for a repository with as few commands as possible, same after clone.
Still better if I needn't do anything for an individual repository with the tricks from 
https://stackoverflow.com/questions/2293498/applying-a-git-post-commit-hook-to-all-current-and-future-repositories

**Comment by danny0838** [comment]
The difference between `git-store-meta.pl -i -s` and `git-store-meta.pl -i && git-store-meta.pl -s` is almost negletible, and the same thing can also be done with shell alias.

OTOH, mixing unrelated commands means intermingling codes for different scopes and a burden for both implementation and for future maintenance and extension, which is not what we want.
