### ISSUE TITLE
git-store-meta usage with large repos

### ISSUE THREAD

**Issue by maizo9** [danny0838/git-store-meta#9]
I have been looking at your tool and several others and they all seem to not be able to handle the following scenario. Suppose you have a large repo with lots of developers working on some of the same files. The file metadata is used to control the build process, which is lengthy due to the size of the project; the metadata is limited to file access and modification times.
How do you handle the file metadata when a developer decides to pull the official repo or merges his/her code with the official repo, and the official repo contains changes to the same files that he/she is working on? Obviously, you want to preserve the file changes so a file contents merge will need to occur but what to do with the metadata? What if the metadata in the official repo points to a time earlier than the metadata for such file in the developers node? What if the opposite is true. There are several scenarios at play in here but I think the 2 described above are the main ones.

I am working on a "solution" to the issue above that uses an alias for the git pull command to identify the differences between the official repo and the developer's repo and stores them to a file. The same alias invokes git-store-meta to apply the metadata store contents to the developer repo files but only if the files are not identified as been changed prior to the git pull operation. If the files are changed it leaves the metadata untouched.

I don't see this as an issue but more of an enhancement. What are your thoughts on this?

**Comment by danny0838** [comment]
I don't get you. Maybe you could state more clear for:
1. What is something you think you should be informed and you aren't. (So that we could improve our documentation.)
2. What is the behavior you expected in what specific case, and git-store-meta doesn't do in this way. (So that we could implement a fix or a new feature.)
3. What is the relation between the above questions with "large repos"?

For the "how does git-meta-store do when ..." questions it should be a lot easier to simply make a test. And you can check how it actually works and whether the behavior is what you expected.

**Comment by maizo9** [comment]
Hi Danny,
Sorry for the confusion. I’ll try to explain the situation better. First of all, git-store-meta is working in this scenario as expected, when called with the apply action after the git pull command it updates the file metadata for all files after the files have been pulled from the remote repo. I also configured the git hooks for pre-commit and post-checkout to adjust the metadata as needed. No issue with these operations at all.

However, the git pull followed by git-meta-store apply command sequence leads to issues. That is because applying metadata from the remote repo leads to an inconsistent built product when the same files are changed by the local and remote repos. The question I posed to you was as follows: Should the tool update/not update the metadata when both the local and remote repos have changed the same file?  If the metadata is updated using the information from the remote repo then the built product may be not be built when it should, because the metadata in the remote repo could be older than the metadata for the derived products in the local node. If the metadata in the remote repo is newer than the derived products metadata in the current repo then the derived products will be built, that could lead to extra products been built, which I believe is the better but not perfect solution to this dilema.

Does that help? I did not wanted to show this as a bug but I could not get it to show in that way. I thought of this more like an enhancement or new feature where you allow a file that contains a whitelist of files that will not have their metadata updated even though they are part of the metadata store.

Thanks,
Maizo

**Comment by danny0838** [comment]
A big reason why Git does not support recording file modified time natively is because it breaks time-based build. If your project requires a file time based build, it's probably a case that file modified time need not be recorded. I would be curious about what your project is if it does need.

**Comment by maizo9** [comment]
Hi Danny,
I hear you. However, by not recording modified file times git breaks time based builds anyways because when you do a "git pull" all files have the current time as their modified times. If you are using view paths then the local node products will need to be rebuilt because all the source files modification times are newer than the products on the view path node.

The issue with our builds is not what is built; is actually the size and complexity of the project. The builds can take anything from 1-4 hours. The choice for Git was made for other smaller and more git-friendly projects and this one was left alone until now. The request to move it to git came on the base of trying to avoid having to support multiple source management systems in the same environment.

I did changed git-meta-store.pl to support reading a file with a white-list of files to skip the metadata adjustment during the apply. I am not familiar with perl but was able to cobble some code to basically open the white-list file, if it exists; and grep for the file I am about to modify in this list. If I find the file, then I skip the metadata modification for both mtime and atime. 

Thanks,
Maizo

**Comment by danny0838** [comment]
No, when you do a "git pull", only **files changed by the merge** have the current time as their modified times, and they should of course rebuilt since they are changed anyway. If this is not your case, you should report this issue to official Git, since Git is essentially made to be compatible with time-based built.

**Comment by maizo9** [comment]
You are correct from the perspective of the git pull but following the git pull with a metadata update changes the metadata for ALL the files not just the changed ones which is where the issue comes into play.

**Comment by danny0838** [comment]
Well, believe it or not, I never see the behavior you described as a long time Git user. If you don't use git-store-meta, don't install custom hooks, a clean install of Git in the latest version never touch files that are not changed by a pull. If it doesn't work in this way, you should report to official Git. I could not offer anymore help in this aspect.

**Comment by danny0838** [comment]
Close stale issue. Response if you still have further question or information.
